---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitcoin-client
  name: bitcoin-client
spec:
  ports:
    - port: 8332
      targetPort: 8332
  selector:
    app: bitcoin-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bitcoin-client
  name: bitcoin-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bitcoin-client
    spec:
      containers:
      - image: jkmart/bitcoin-client:fuse
        name: bitcoin-client
        ports:
        - containerPort: 8332
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
        volumeMounts:
        - name: data
          mountPath: /opt/graphsense/data
        - name: config
          mountPath: /opt/graphsense/
          readOnly: true
      restartPolicy: Always
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      volumes:
      # Add the client config file
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: btc-client-config
          # An array of keys from the ConfigMap to create as files
          items:
            - key: "client.conf"
              path: "client.conf"
  serviceName: bitcoin-client
  selector:
    matchLabels:
      app: bitcoin-client
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1000Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: btc-client-config
data:
  # file-like keys
  client.conf: |
    # server=1 tells Bitcoin-Qt and bitcoind to accept JSON-RPC commands
    server=1
    rpcclienttimeout=30
    # By default, only RPC connections from localhost are allowed.
    # Specify as many rpcallowip= settings as you like to allow connections from other hosts,
    # either as a single IPv4/IPv6 or with a subnet specification.
    rpcport=8332
    # API requests need to access non-wallet blockchain transactions by their IDs,
    # following is used enable the transaction index in the Bitcoin Core database
    txindex=1
