---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btc-parse-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: btc-parse-job
  name: btc-parse-job
spec:
  template:
    spec:
      containers:
        - image: jkmart/graphsense-blocksci-ingest:0.5.2
          imagePullPolicy: IfNotPresent
          name: parse
          command: ["blocksci_parser"]
          args: ["/opt/graphsense/blocksci.cfg", "update"]
          resources:
            requests:
              cpu: "4"
              memory: "90Gi"
          volumeMounts:
            - name: data
              mountPath: /var/data/block_data/
              readOnly: true
            - name: parse
              mountPath: /var/data/blocksci_data/
            - name: config
              mountPath: /opt/graphsense/
              readOnly: true
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-bitcoin-client-0
        - name: parse
          persistentVolumeClaim:
            claimName: btc-parse-claim
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: graphsense-parse-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: blocksci.json
                path: blocksci.cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphsense-parse-config
data:
  # file-like keys
  blocksci.json: >
    {
      "chainConfig": {
        "coinName": "bitcoin",
        "dataDirectory": "/var/data/blocksci_data",
        "pubkeyPrefix": [
          0
        ],
        "scriptPrefix": [
          5
        ],
        "segwitActivationHeight": 481824,
        "segwitPrefix": "bc"
      },
      "parser": {
        "disk": {
          "blockMagic": 3652501241,
          "coinDirectory": "/var/data/block_data",
          "hashFuncName": "doubleSha256"
        },
        "maxBlockNum": -6
      },
      "version": 5
    }
