apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-master
  name: spark-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - env:
        - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_MODE
          value: master
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        - name: SPARK_RPC_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_SSL_ENABLED
          value: "no"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        image: docker.io/bitnami/spark:3.2.1-debian-10-r104
        name: spark-master
        command: []
        args: []
        ports:
        - containerPort: 8080
        - containerPort: 7077
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
      restartPolicy: Always
  selector:
    matchLabels:
      app: spark-master
