apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-master
  name: spark-master
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 8080
    targetPort: 8080
  - name: master
    port: 7077
    targetPort: 7077
  selector:
    app: spark-master
