apiVersion: v1
kind: Service
metadata:
  labels:
    app: transformation
  name: transformation
spec:
  ports:
  - name: "spark-ui"
    port: 4040
    targetPort: 4040
  - name: "spark-driver"
    port: 4041
    targetPort: 4041
  - name: "spark-blockmgr"
    port: 4042
    targetPort: 4042
  selector:
    app: transformation
